# Домашнее задание 1

**Тема “Вычисления с помощью Numpy”**

Задание 1

In [1]:
import numpy as np

In [ ]:
# Матрица a из 2 признаков и 5 наблюдений:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
# Средние значения по каждому признаку:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

In [ ]:
# Получим центрированную матрицу:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [ ]:
# Скалярное произведение признаков матрицы a:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [ ]:
# Количество наблюдений матрицы a:
n = a.shape[0]
n

5

In [ ]:
# Несмещенная оценка ковариации:
a_centered_sp / (n - 1)

2.0

Задание 4

In [ ]:
# Матрица ковариаций:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

**Тема “Работа с данными в Pandas”**

Задание 1

In [2]:
import pandas as pd

In [3]:
# Создаем датафрейм authors:
authors = pd.DataFrame({"author_id": [1, 2, 3],
                        "author_name": ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [4]:
# Создаем датафрейм book:
books = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3],
                     "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     "price": [450, 300, 350, 500, 450, 370, 290]})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [5]:
# Объединим authors и books по столбцу author_id:
authors_price = pd.merge(authors, books, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [6]:
# Создадим датафрейм top5 с пятью самыми дорогими книгами:
top5 = authors_price.nlargest(5, 'price')
top5 = top5.reset_index(drop=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

Задание 4

In [7]:
# Создадим датафрейм authors_stat, содержащий данные о максимальной, минимальной и средней ценах за книгу каждого автора:
max_price = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price': 'max_price'})
min_price = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price': 'min_price'})
mean_price = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price': 'mean_price'})
authors_stat = pd.concat([max_price, min_price, mean_price], axis=1)
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

Задание 5*

In [9]:
# Добавим столбец cover:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [39]:
# Посчитаем для каждого автора суммарную стоимость книг в твердой и мягкой обложке:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info.fillna(0, inplace=True)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [40]:
# Запишем датасет book_info в файл book_info.pkl:
book_info.to_pickle('book_info.pkl')

In [43]:
# Выгрузим датасет из файла book_info.pkl:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0